"""create users and auth identities

Revision ID: 00b7eb7275bc
Revises:
Create Date: 2026-10-07 16:21:07.170856
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "00b7eb7275bc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("handle", sa.String(length=30), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("weight_unit", sa.String(length=2), server_default="lb", nullable=False),
        sa.Column("friend_code", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "friend_code ~ '^[A-HJKMNP-Z2-9]{8}$'", name=op.f("ck_users_friend_code_format")
        ),
        sa.CheckConstraint("handle ~ '^[a-z0-9_]{3,30}$'", name=op.f("ck_users_handle_format")),
        sa.CheckConstraint("weight_unit IN ('lb', 'kg')", name=op.f("ck_users_weight_unit")),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_users_name_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("friend_code", name=op.f("uq_users_friend_code")),
        sa.UniqueConstraint("handle", name=op.f("uq_users_handle")),
    )
    op.create_index(
        "ix_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "auth_identities",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('apple', 'google')", name=op.f("ck_auth_identities_provider")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_identities")),
        sa.UniqueConstraint(
            "provider", "subject", name=op.f("uq_auth_identities_provider_subject")
        ),
        sa.UniqueConstraint(
            "user_id", "provider", name=op.f("uq_auth_identities_user_id_provider")
        ),
    )
    op.create_index(
        op.f("ix_auth_identities_user_id"), "auth_identities", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_identities_user_id"), table_name="auth_identities")
    op.drop_table("auth_identities")
    op.drop_index("ix_users_email_lower", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
