"""friends

Revision ID: a83570c49196
Revises: 47928c100f42
Create Date: 2026-10-07 17:30:09.916982
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a83570c49196"
down_revision: str | None = "47928c100f42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friend_requests",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("from_user_id", sa.UUID(), nullable=False),
        sa.Column("to_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("from_user_id <> to_user_id", name=op.f("ck_friend_requests_not_self")),
        sa.ForeignKeyConstraint(
            ["from_user_id"],
            ["users.id"],
            name=op.f("fk_friend_requests_from_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_user_id"],
            ["users.id"],
            name=op.f("fk_friend_requests_to_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_friend_requests")),
        sa.UniqueConstraint(
            "from_user_id", "to_user_id", name=op.f("uq_friend_requests_from_user_id_to_user_id")
        ),
    )
    op.create_index(
        op.f("ix_friend_requests_to_user_id"), "friend_requests", ["to_user_id"], unique=False
    )
    op.create_table(
        "friendships",
        sa.Column("user_low_id", sa.UUID(), nullable=False),
        sa.Column("user_high_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("user_low_id < user_high_id", name=op.f("ck_friendships_ordered_pair")),
        sa.ForeignKeyConstraint(
            ["user_high_id"],
            ["users.id"],
            name=op.f("fk_friendships_user_high_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_low_id"],
            ["users.id"],
            name=op.f("fk_friendships_user_low_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_low_id", "user_high_id", name=op.f("pk_friendships")),
    )
    op.create_index(
        op.f("ix_friendships_user_high_id"), "friendships", ["user_high_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_friendships_user_high_id"), table_name="friendships")
    op.drop_table("friendships")
    op.drop_index(op.f("ix_friend_requests_to_user_id"), table_name="friend_requests")
    op.drop_table("friend_requests")
    # ### end Alembic commands ###
