"""email password auth

Revision ID: 47928c100f42
Revises: 8f071460db06
Create Date: 2026-10-07 17:13:14.694803
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "47928c100f42"
down_revision: str | None = "8f071460db06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Switch from Apple/Google sign-in to email + password.
    op.drop_index(op.f("ix_auth_identities_user_id"), table_name="auth_identities")
    op.drop_table("auth_identities")
    # Accounts made via Apple/Google (or the old dev sign-in) have no password, so
    # nobody can sign in to them any more. Pre-launch these are only test accounts;
    # remove them (sessions cascade) so password_hash and email can be required.
    op.execute("DELETE FROM users")
    op.add_column("users", sa.Column("password_hash", sa.String(length=255), nullable=False))
    op.alter_column("users", "email", existing_type=sa.VARCHAR(length=320), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "email", existing_type=sa.VARCHAR(length=320), nullable=True)
    op.drop_column("users", "password_hash")
    op.create_table(
        "auth_identities",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("provider", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("subject", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=320), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_used_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('apple', 'google')",
            name=op.f("ck_auth_identities_provider"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_identities")),
        sa.UniqueConstraint(
            "provider",
            "subject",
            name=op.f("uq_auth_identities_provider_subject"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "user_id",
            "provider",
            name=op.f("uq_auth_identities_user_id_provider"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_auth_identities_user_id"), "auth_identities", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
